name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  actions: write
  contents: write

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest

      - name: Install Dependencies
        run: shards install --production

      - name: Compile Binaries
        run: |
          crystal build src/main.cr --no-debug --release -o crimson
          tar -zcf crimson-${{ github.ref_name }}-linux-x86_64.tar.gz crimson

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: crimson-linux
          path: |
            crimson
            crimson-${{ github.ref_name }}-linux-x86_64.tar.gz

  windows:
    needs: linux
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest

      - name: Install Dependencies
        run: shards install --production

      - name: Compile Binaries
        run: |
          crystal build src\main.cr --no-debug --release -o crimson.exe
          $compress = @{
            Path = "crimson.exe", "*.dll"
            DestinationPath = "crimson-${{ github.ref_name }}-windows-x86_64-msvc.zip"
          }
          Compress-Archive @compress

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: crimson-windows
          path: |
            crimson.exe
            crimson-${{ github.ref_name }}-windows-x86_64-msvc.zip

  release:
    needs: windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
          pattern: crimson-*
          merge-multiple: true

      - name: Prepare Artifacts
        run: |
          mv artifacts/* .
          sha256sum crimson crimson.exe > checksums.txt

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          gh release create ${{ github.ref_name }} -pt ${{ github.ref_name }}
          gh release upload ${{ github.ref_name }} checksums.txt
          gh release upload ${{ github.ref_name }} crimson-${{ github.ref_name }}-linux-x86_64.tar.gz
          gh release upload ${{ github.ref_name }} crimson-${{ github.ref_name }}-windows-x86_64-msvc.zip
